version: '3.8'

services:
  trading-buddy:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped